### ISSUE TITLE
Assertions for performance metrics

### ISSUE THREAD

**Issue by wurde** [rails/rails-perftest#30]
I expected examples on how to assert global and testcase-specific assertions on performance metrics. For example, ensuring no single integration test runs for longer than a second, but allowing local test case overrides for special cases.

**Comment by senny** [comment]
@wurde sorry but this is not what `rails-perftest` currently does. The functionality of the gem is a one-to-one extraction of what Rails used to provide in core. We decided to extract that functionality because it was not widely used. At this point, this gem only provides backwards compatibility for people that rely on this functionality.

At the moment there is no active maintainer to move the development further than backwards compatibility.

If someone is interested to step up and work on this, please drop me a line.
